# Generated by Django 3.1 on 2020-08-10 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Categoria', models.CharField(choices=[('1', 'Conferencia'), ('2', 'Seminario'), ('3', 'Curso'), ('4', 'Congreso')], max_length=1)),
                ('Lugar', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('FechaInicio', models.DateField()),
                ('FechaFin', models.DateField()),
                ('Tipo', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], max_length=1)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEventos.usuario')),
            ],
        ),
    ]
