# Generated by Django 3.1 on 2020-08-11 06:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('GestionEventos', '0003_auto_20200811_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEventos.usuario'),
        ),
    ]
