# Generated by Django 3.1 on 2020-08-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEventos', '0005_auto_20200812_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='event_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
