# Generated by Django 3.1 on 2020-08-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEventos', '0006_auto_20200812_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='Evento',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionEventos.usuario'),
        ),
    ]
