# Generated by Django 3.1 on 2020-08-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEventos', '0008_auto_20200812_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='User',
            new_name='event_user',
        ),
    ]
