# Generated by Django 3.1 on 2020-08-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionEventos', '0010_auto_20200812_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='thumbnail',
            field=models.ImageField(default='event_thumbnails/default.png', upload_to='event_thumbnails', verbose_name='Imagen'),
        ),
    ]
